---
- name: Include data persintency
  tags: magneto
  include: ../../silpion.lib/tasks/datapersistency.yml

- name: Download Magento
  tags: magento
  when: magento_download
  include: ../../silpion.lib/tasks/get_url.yml
  vars:
    url: "{{ magento_download_url }}"
    filename: "{{ magento_download_package }}"

- name: Upload installation archive
  tags: magento
  include: ../../silpion.lib/tasks/copy.yml
  vars:
    filename: "{{ magento_download_package }}"

- name: Extract Magento
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ magento_download_package }}"
    dest: "{{ lib_persistent_data_path_remote }}/"
    copy: false

- name: Change owner and group
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  file:
    state: directory
    path: "{{ lib_persistent_data_path_remote }}/{{ magento_archive_subdir|default('magento') }}"
    owner: "{{ magento_webuser }}"
    group: "{{ magento_webgroup }}"
    recurse: true

- name: Move to Magento-Root-Dir
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  command:
    "rsync -av
    -p --chmod=Du=rwx --chmod=Dg=rx --chmod=Do= --chmod=Fu=rw --chmod=Fg=r --chmod=Fo=
    {{ lib_persistent_data_path_remote }}/{{ magento_archive_subdir|default('magento') }}/
    {{ magento_root }}/"

    #rsync_opts="--chmod=D2750,--chmod=F640"
    #
- name: Create Magento-Install script
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  template:
    src: magento-install.j2
    dest: "{{ magento_bin_dir }}/magento-install.sh"

- name: Remove app/etc/local.xml if exists
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  file:
    state: absent
    path: "{{ magento_root }}/app/etc/local.xml"

- name: Install Magento local.xml.template
  tags: magento
  become: "{{ lib_action_become_enable }}"
  become_user: "{{ lib_action_become_user }}"
  template:
    src: "{{ magento_local_template|default('local.xml.template.j2') }}"
    dest: "{{ magento_root }}/app/etc/local.xml.template"

- name: Notify install
  tags: magento
  notify: run magento install
  command: /bin/true
